--Oracle - INSTR (PATINDEX - SQL Server)

--PATINDEX - INSTR

SELECT  HORA,
        TO_NUMBER(SUBSTR(HORA,1,INSTR(HORA,':')-1)) HORA,
        TO_NUMBER(SUBSTR(HORA,(INSTR(HORA,':')+1),2)) MINUTO,
        (TO_NUMBER(SUBSTR(HORA,1,INSTR(HORA,':')-1)) +
         TO_NUMBER(SUBSTR(HORA,(INSTR(HORA,':')+1),2))) AS VLRDECIMAL
FROM ZPFFINANC_IMP