CREATE TABLESPACE RM_DADOS 
   DATAFILE 'C:\app\Administrador\oradata\EXEMPLO_DBS\RMDADOS1.DAT' SIZE 120M  AUTOEXTEND ON NEXT 10M
   DEFAULT STORAGE ( INITIAL 8K
		     NEXT    256K
		     MINEXTENTS 1
		     MAXEXTENTS 121
		     PCTINCREASE 50);

CREATE TABLESPACE RM_DADOS_FF
   DATAFILE 'C:\app\Administrador\oradata\EXEMPLO_DBS\RMDADOS2.DAT' SIZE 100M  AUTOEXTEND ON NEXT 10M
   DEFAULT STORAGE ( INITIAL 8K
		     NEXT    256K
		     MINEXTENTS 1
		     MAXEXTENTS 121
		     PCTINCREASE 0);

CREATE TABLESPACE RM_INDICES  
   DATAFILE 'C:\app\Administrador\oradata\EXEMPLO_DBS\RMIND1.IDX' SIZE 30M  AUTOEXTEND ON NEXT 10M
   DEFAULT STORAGE ( INITIAL 8K
		     NEXT    84K
		     MINEXTENTS 1
		     MAXEXTENTS 121
		     PCTINCREASE 50);

CREATE TEMPORARY TABLESPACE RM_TMP
   TEMPFILE 'C:\app\Administrador\oradata\EXEMPLO_DBS\RMTMP1.DAT' SIZE 10M  AUTOEXTEND ON NEXT 5M
EXTENT MANAGEMENT LOCAL;