CREATE 	USER rm
	IDENTIFIED BY rm
	DEFAULT TABLESPACE  RM_DADOS
	TEMPORARY TABLESPACE RM_TMP;

CREATE  USER sysdba
	IDENTIFIED BY masterkey
	DEFAULT TABLESPACE  RM_DADOS
	TEMPORARY TABLESPACE RM_TMP;


CREATE ROLE ACESSO_RM;

GRANT CONNECT,DBA,RESOURCE TO RM;

GRANT CONNECT, RESOURCE TO ACESSO_RM;

GRANT CONNECT,RESOURCE,ACESSO_RM TO SYSDBA;

ALTER 	USER SYSDBA
 	DEFAULT ROLE ALL;