-- Quebra Hard Lock
-- 11.40

select * from ZGCOLIGADA_HL

-------------------------------------------------------------
-- GCOLIGADA ------------------------------------------------
-------------------------------------------------------------
SELECT * INTO ZGCOLIGADA_HL
FROM GCOLIGADA
GO

UPDATE FERTEMP_SODEXO..GCOLIGADA SET 
		NOMEFANTASIA = A.NOMEFANTASIA,
		CGC = A.CGC,
		NOME = A.NOME,
		INSCRICAOESTADUAL = A.INSCRICAOESTADUAL,
		TELEFONE = A.TELEFONE,
		FAX = A.FAX,
		EMAIL = A.EMAIL,
		RUA = A.RUA,
		NUMERO = A.NUMERO,
		COMPLEMENTO = A.COMPLEMENTO,
		BAIRRO = A.BAIRRO,
		CIDADE = A.CIDADE,
		ESTADO = A.ESTADO,
		PAIS = A.PAIS,
		CEP = A.CEP,
		CONTROLACGC = A.CONTROLACGC,
		CONTROLE1 = A.CONTROLE1,
		CONTROLE2 = A.CONTROLE2,
		CONTROLE3 = A.CONTROLE3,
		IDIMAGEM = A.IDIMAGEM,
		PRODUTORRURAL = A.PRODUTORRURAL,
		ATIVO = A.ATIVO,
		CODEXTERNO = A.CODEXTERNO,
		IMPORTADA = A.IMPORTADA,
		DATALIMITELICENCAS = A.DATALIMITELICENCAS			
FROM CorporeRM_SHL..GCOLIGADA A
WHERE FERTEMP_SODEXO..GCOLIGADA.CODCOLIGADA = A.CODCOLIGADA
AND FERTEMP_SODEXO..GCOLIGADA.CODCOLIGADA = 1
GO

-------------------------------------------------------------
-- GPARAMS --------------------------------------------------
-------------------------------------------------------------
SELECT * INTO ZGPARAMS_HL
FROM GPARAMS
GO

UPDATE FERTEMP_SODEXO..GPARAMS
	SET VERSAOBASE = A.VERSAOBASE,
		CONTROLE = A.CONTROLE,
		ERROSATUALIZ = A.ERROSATUALIZ,
		BASE = A.BASE,
		UNIFIEDLOGON = A.UNIFIEDLOGON,
		PORTOMSG = A.PORTOMSG,
		UPCASELOGIN = A.UPCASELOGIN,
		USAULTIMACOLIGADA = A.USAULTIMACOLIGADA,
		NUMTENTLOGIN = A.NUMTENTLOGIN,
		TEMPOUSRBLOQ = A.TEMPOUSRBLOQ,
		SEGURANCAGERADOR = A.SEGURANCAGERADOR,
		MAXACESSOS = A.MAXACESSOS,
		PAIS = A.PAIS,
		NUMDIASLOGREL = A.NUMDIASLOGREL,
		MAXACESSOSNET = A.MAXACESSOSNET,
		URLPORTAL = A.URLPORTAL,
		SIMBOLOMOEDA = A.SIMBOLOMOEDA,
		DIASRELAGENDADO = A.DIASRELAGENDADO,
		BKUSACARGAREMOTA = A.BKUSACARGAREMOTA,
		BKIPSERVIDORCARGAREMOTA = A.BKIPSERVIDORCARGAREMOTA,
		BKIPSERVIDORGLOBAL = A.BKIPSERVIDORGLOBAL,
		STARTPSW = A.STARTPSW,
		USACODUSUARIOREDE = A.USACODUSUARIOREDE,
		LDAPLOGON = A.LDAPLOGON,
		LDAPGROUP = A.LDAPGROUP,
		LDAPPATH = A.LDAPPATH,
		LDAPADMINPASSWORD = A.LDAPADMINPASSWORD,
		LDAPREMOVEUSER = A.LDAPREMOVEUSER,
		USASEGCONSSQL = A.USASEGCONSSQL,
		USABLOQSEGCONSSQL = A.USABLOQSEGCONSSQL,
		GRAVALOGEMAIL = A.GRAVALOGEMAIL,
		LIMPALOGEMAIL = A.LIMPALOGEMAIL,
		LICENCACORPORATIVA = A.LICENCACORPORATIVA,
		NUMLICENCASFULL = A.NUMLICENCASFULL,
		USALICENCATOTVS = A.USALICENCATOTVS,
		CANUSESTARTPSW = A.CANUSESTARTPSW,
		LICENCESERVERADDRESS = A.LICENCESERVERADDRESS,
		LICENCESERVERPORT = A.LICENCESERVERPORT,
		CONTROLELIC = A.CONTROLELIC,
		DIASLOGUSRACTION = A.DIASLOGUSRACTION,
		DEFAULTSENDERMAIL = A.DEFAULTSENDERMAIL,
		RESOURCEWS = A.RESOURCEWS,
		RESOURCEWSENABLED = A.RESOURCEWSENABLED,
		LDAPPATHINTEG = A.LDAPPATHINTEG,
		USASEGURANCAFILIAL = A.USASEGURANCAFILIAL,
		USASEGURANCACCUSTO = A.USASEGURANCACCUSTO,
		USARUSUARIOCOMOREMETENTEEMAIL = A.USARUSUARIOCOMOREMETENTEEMAIL,
		IDCUSTOMLOGO = A.IDCUSTOMLOGO,
		TYPECUSTOMLOGO = A.TYPECUSTOMLOGO,
		LICENCESERVERSUPERVISORALERT = A.LICENCESERVERSUPERVISORALERT,
		EMERGENCYKEY = A.EMERGENCYKEY
FROM CorporeRM_SHL..GPARAMS A
GO

-------------------------------------------------------------
-- GLICENCA -------------------------------------------------
-------------------------------------------------------------
SELECT * INTO ZGLICENCA_HL
FROM GLICENCA
GO

DELETE FROM GLICENCA
GO

INSERT INTO GLICENCA
SELECT *
FROM CorporeRM_SHL..GLICENCA
WHERE CODCOLIGADA = 1
GO

-------------------------------------------------------------
-- GSISTEMA -------------------------------------------------
-------------------------------------------------------------
SELECT * INTO ZGSISTEMA_HL
FROM GSISTEMA

INSERT INTO GSISTEMA
SELECT *
FROM CorporeRM_SHL..GSISTEMA
WHERE CODSISTEMA COLLATE DATABASE_DEFAULT NOT IN (SELECT CODSISTEMA FROM GSISTEMA )
GO

UPDATE FERTEMP_SODEXO..GSISTEMA
		SET CODSISTCOMERCIAL = A.CODSISTCOMERCIAL,
			NOMESISTEMA = A.NOMESISTEMA,
			CODCOLIGADAMASTER = A.CODCOLIGADAMASTER,
			NUMMAXCOLIGADAS = A.NUMMAXCOLIGADAS,
			CONTROLE = A.CONTROLE,
			VERSAOEXIGIDA = A.VERSAOEXIGIDA,
			VERSAOATIVADA = A.VERSAOATIVADA,
			VERSAOMINIMA = A.VERSAOMINIMA,
			VERSAOPAGTO = A.VERSAOPAGTO,
			DESCRICAO = A.DESCRICAO,
			LICENCESERVERSLOT = A.LICENCESERVERSLOT,
			NUMLICENCASLIGHT = A.NUMLICENCASLIGHT
FROM CorporeRM_SHL..GSISTEMA A
WHERE FERTEMP_SODEXO..GSISTEMA.CODSISTEMA COLLATE DATABASE_DEFAULT = A.CODSISTEMA
GO